module.exports = [
    {
      No: 1,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0691',
      Site_Name: 'IBASUF',
      File_Name: 'PAB0691_IBASUF',
      Longitude: 132.37775,
      Latitude: -1.4239,
      Survey: 'Layak',
      Status_Dokumen: 'Ok'
    },
    {
      No: 2,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0694',
      Site_Name: 'IROHMRAR',
      File_Name: 'PAB0694_IROHMRAR',
      Longitude: 132.38544,
      Latitude: -1.43749,
      Survey: 'Layak',
      Status_Dokumen: 'Done'
    },
    {
      No: 3,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0682',
      Site_Name: 'AITINYO',
      File_Name: 'PAB0682_AITINYO',
      Longitude: 132.38184,
      Latitude: -1.43989,
      Survey: 'Layak',
      Status_Dokumen: 'Ok'
    },
    {
      No: 4,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0684',
      Site_Name: 'SRIS',
      File_Name: 'PAB0684_SRIS',
      Longitude: 132.39551,
      Latitude: -1.43611,
      Survey: 'Layak',
      Status_Dokumen: 'Done'
    },
    {
      No: 5,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0685',
      Site_Name: 'KAMRO',
      File_Name: 'PAB0685_KAMRO',
      Longitude: 132.37722,
      Latitude: -1.50602,
      Survey: 'Layak',
      Status_Dokumen: 'Ok'
    },
    {
      No: 6,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0686',
      Site_Name: 'KARSU',
      File_Name: 'PAB0686_KARSU',
      Longitude: 132.39551,
      Latitude: -1.44606,
      Survey: 'Layak',
      Status_Dokumen: 'Ok'
    },
    {
      No: 7,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0687',
      Site_Name: 'TEHAK KECIL',
      File_Name: 'PAB0687_TEHAK KECIL',
      Longitude: 132.38966,
      Latitude: -1.42646,
      Survey: 'Layak',
      Status_Dokumen: 'Done',
      Keterangan: 'Geser / Reloc'
    },
    {
      No: 8,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0683',
      Site_Name: 'IROHE',
      File_Name: 'PAB0683_IROHE',
      Longitude: 132.38256,
      Latitude: -1.44239,
      Survey: 'Layak',
      Status_Dokumen: 'Done'
    },
    {
      No: 9,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0688',
      Site_Name: 'SIRA AYA',
      File_Name: 'PAB0688_SIRA AYA',
      Longitude: 132.38513,
      Latitude: -1.4308,
      Survey: 'Layak',
      Status_Dokumen: 'Today'
    },
    {
      No: 10,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0692',
      Site_Name: 'SOWAI SAU',
      File_Name: 'PAB0692_SOWAI SAU',
      Longitude: 132.41196,
      Latitude: -1.4373,
      Survey: 'Layak',
      Status_Dokumen: 'Ok'
    },
    {
      No: 11,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0689',
      Site_Name: 'KOROM',
      File_Name: 'PAB0689_KOROM',
      Longitude: 132.38759,
      Latitude: -1.42801,
      Survey: 'Layak',
      Status_Dokumen: 'Ok',
      Keterangan: 'Geser / Reloc'
    },
    {
      No: 12,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0690',
      Site_Name: 'SUMANIS',
      File_Name: 'PAB0690_SUMANIS',
      Longitude: 132.37991,
      Latitude: -1.47553,
      Survey: 'Layak',
      Status_Dokumen: 'Today'
    },
    {
      No: 13,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0695',
      Site_Name: 'BOFAIT',
      File_Name: 'PAB0695_BOFAIT',
      Longitude: 132.38756,
      Latitude: -1.42539,
      Survey: 'Layak',
      Status_Dokumen: 'Today'
    },
    {
      No: 14,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0696',
      Site_Name: 'AFKREM',
      File_Name: 'PAB0696_AFKREM',
      Longitude: 132.39294,
      Latitude: -1.42868,
      Survey: 'Layak',
      Status_Dokumen: 'Today'
    },
    {
      No: 15,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0697',
      Site_Name: 'WIHO',
      File_Name: 'PAB0697_WIHO',
      Longitude: 132.40985,
      Latitude: -1.42116,
      Survey: 'Layak',
      Status_Dokumen: 'Done',
      Keterangan: 'Revisi-Geser'
    },
    {
      No: 16,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0693',
      Site_Name: 'SUBIN',
      File_Name: 'PAB0693_SUBIN',
      Longitude: 132.41408,
      Latitude: -1.47992,
      Survey: 'Layak',
      Status_Dokumen: 'Done'
    },
    {
      No: 17,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO',
      Cell_ID: 'PAB0698',
      Site_Name: 'KAMRO SELATAN',
      File_Name: 'PAB0698_KAMRO SELATAN',
      Longitude: 132.37514,
      Latitude: -1.49912,
      Survey: 'Layak',
      Status_Dokumen: 'Today'
    },
    {
      No: 18,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO TENGAH',
      Cell_ID: 'PAB0990_Ex_PAB0804',
      Site_Name: 'SABUN',
      File_Name: 'PAB0990_Ex_PAB0804_SABUN',
      Longitude: 132.28313,
      Latitude: -1.50737,
      Survey: 'Relok',
      Status_Dokumen: 'Done'
    },
    {
      No: 19,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO TENGAH',
      Cell_ID: 'PAB0805',
      Site_Name: 'EWAY',
      File_Name: 'PAB0805_EWAY',
      Longitude: 132.2069,
      Latitude: -1.43889,
      Survey: 'Layak',
      Status_Dokumen: 'Ok'
    },
    {
      No: 20,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO TENGAH',
      Cell_ID: 'PAB0806',
      Site_Name: 'ITIGAH',
      File_Name: 'PAB0806_ITIGAH',
      Longitude: 132.31073,
      Latitude: -1.5272,
      Survey: 'Layak',
      Status_Dokumen: 'Ok'
    },
    {
      No: 21,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO TENGAH',
      Cell_ID: 'PAB0991_Ex_PAB0807',
      Site_Name: 'EROK WERO',
      File_Name: 'PAB0991_Ex_PAB0807_EROK WERO',
      Longitude: 132.34436,
      Latitude: -1.45354,
      Survey: 'Relok',
      Status_Dokumen: 'Done'
    },
    {
      No: 22,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO TENGAH',
      Cell_ID: 'PAB0992_Ex_PAB0808',
      Site_Name: 'WRAITTU',
      File_Name: 'PAB0992_Ex_PAB0808_WRAITTU',
      Longitude: 132.29689,
      Latitude: -1.44188,
      Survey: 'Relok',
      Status_Dokumen: 'Done'
    },
    {
      No: 23,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO TENGAH',
      Cell_ID: 'PAB0803',
      Site_Name: 'YAKSORO',
      File_Name: 'PAB0803_YAKSORO',
      Longitude: 132.33199,
      Latitude: -1.44536,
      Survey: 'Layak',
      Status_Dokumen: 'Ok',
      Keterangan: 'Revisi-Geser'
    },
    {
      No: 24,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO TENGAH',
      Cell_ID: 'PAB0809',
      Site_Name: 'ASNAIF',
      File_Name: 'PAB0809_ASNAIF',
      Longitude: 132.320207,
      Latitude: -1.44811,
      Survey: 'Layak',
      Status_Dokumen: 'Ok'
    },
    {
      No: 25,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO TENGAH',
      Cell_ID: 'PAB0810',
      Site_Name: 'IROH SOHSER',
      File_Name: 'PAB0810_IROH SOHSER',
      Longitude: 132.35519,
      Latitude: -1.45119,
      Survey: 'Layak',
      Status_Dokumen: 'Today'
    },
    {
      No: 26,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO TENGAH',
      Cell_ID: 'PAB0812',
      Site_Name: 'TOHMRI',
      File_Name: 'PAB0812_TOHMRI',
      Longitude: 132.27485,
      Latitude: -1.49533,
      Survey: 'Layak',
      Status_Dokumen: 'Ok'
    },
    {
      No: 27,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO TENGAH',
      Cell_ID: 'PAB0811',
      Site_Name: 'FRAMBOH',
      File_Name: 'PAB0811_FRAMBOH',
      Longitude: 132.32433,
      Latitude: -1.4213,
      Survey: 'Layak',
      Status_Dokumen: 'Today'
    },
    {
      No: 28,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO UTARA',
      Cell_ID: 'PAB0699',
      Site_Name: 'TEHAK BESAR',
      File_Name: 'PAB0699_TEHAK BESAR',
      Longitude: 132.36053,
      Latitude: -1.35049,
      Survey: 'Layak',
      Status_Dokumen: 'Today'
    },
    {
      No: 29,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO UTARA',
      Cell_ID: 'PAB0700',
      Site_Name: 'FAN',
      File_Name: 'PAB0700_FAN',
      Longitude: 132.35866,
      Latitude: -1.33568,
      Survey: 'Layak',
      Status_Dokumen: 'Ok',
      Keterangan: 'Revisi-Geser'
    },
    {
      No: 30,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO UTARA',
      Cell_ID: 'PAB0702',
      Site_Name: 'ASMURUF TEE',
      File_Name: 'PAB0702_ASMURUF TEE',
      Longitude: 132.36343,
      Latitude: -1.34203,
      Survey: 'Layak',
      Status_Dokumen: 'Ok',
      Keterangan: 'Revisi-Geser'
    },
    {
      No: 31,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO UTARA',
      Cell_ID: 'PAB0703',
      Site_Name: 'TEHAK TEE',
      File_Name: 'PAB0703_TEHAK TEE',
      Longitude: 132.38136,
      Latitude: -1.35052,
      Survey: 'Layak',
      Status_Dokumen: 'Ok'
    },
    {
      No: 32,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO UTARA',
      Cell_ID: 'PAB0704',
      Site_Name: 'FRAMAFIR',
      File_Name: 'PAB0704_FRAMAFIR',
      Longitude: 132.35404,
      Latitude: -1.32541,
      Survey: 'Layak',
      Status_Dokumen: 'Ok'
    },
    {
      No: 33,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO UTARA',
      Cell_ID: 'PAB0705',
      Site_Name: 'SUBRIT',
      File_Name: 'PAB0705_SUBRIET',
      Longitude: 132.33422,
      Latitude: -1.3528,
      Survey: 'Layak',
      Status_Dokumen: 'Done'
    },
    {
      No: 34,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO UTARA',
      Cell_ID: 'PAB0980_Ex_PAB0706',
      Site_Name: 'ISIR',
      File_Name: 'PAB0980_Ex_PAB0706_ISIR',
      Longitude: 132.30365,
      Latitude: -1.33131,
      Survey: 'Relok',
      Status_Dokumen: 'Done'
    },
    {
      No: 35,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO UTARA',
      Cell_ID: 'PAB0707',
      Site_Name: 'BOHWAT',
      File_Name: 'PAB0707_BOHWAT',
      Longitude: 132.35686,
      Latitude: -1.33163,
      Survey: 'Layak',
      Status_Dokumen: 'Ok'
    },
    {
      No: 36,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO UTARA',
      Cell_ID: 'PAB0701',
      Site_Name: 'GOHSAMES',
      File_Name: 'PAB0701_GOHSAMES',
      Longitude: 132.38742,
      Latitude: -1.31473,
      Survey: 'Layak',
      Status_Dokumen: 'Ok'
    },
    {
      No: 37,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AYAMARU BARAT',
      Cell_ID: 'PAB0797',
      Site_Name: 'FANSE',
      File_Name: 'PAB0797_FANSE',
      Longitude: 132.12976,
      Latitude: -1.25275,
      Survey: 'Layak',
      Status_Dokumen: 'Done',
      Keterangan: 'Revisi-Geser'
    },
    {
      No: 38,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AYAMARU BARAT',
      Cell_ID: 'PAB0798',
      Site_Name: 'CHALIAT',
      File_Name: 'PAB0798_CHALIAT',
      Longitude: 132.13258,
      Latitude: -1.24896,
      Survey: 'Layak',
      Status_Dokumen: 'Today',
      Keterangan: 'Revisi-Geser'
    },
    {
      No: 39,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AYAMARU BARAT',
      Cell_ID: 'PAB0799',
      Site_Name: 'SEHU',
      File_Name: 'PAB0799_SEHU',
      Longitude: 132.10574,
      Latitude: -1.21184,
      Survey: 'Layak',
      Status_Dokumen: 'Ok'
    },
    {
      No: 40,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AYAMARU BARAT',
      Cell_ID: 'PAB0800',
      Site_Name: 'TBO',
      File_Name: 'PAB0800_TBO',
      Longitude: 132.13724,
      Latitude: -1.25075,
      Survey: 'Layak',
      Status_Dokumen: 'Done',
      Keterangan: 'Revisi-Geser'
    },
    {
      No: 41,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AYAMARU BARAT',
      Cell_ID: 'PAB0801',
      Site_Name: 'SIEN',
      File_Name: 'PAB0801_SIEN',
      Longitude: 132.12606,
      Latitude: -1.24358,
      Survey: 'Layak',
      Status_Dokumen: 'Done'
    },
    {
      No: 42,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AYAMARU BARAT',
      Cell_ID: 'PAB0802',
      Site_Name: 'SFAKRAKA',
      File_Name: 'PAB0802_SFAKRAKA',
      Longitude: 132.123309,
      Latitude: -1.2408,
      Survey: 'Layak',
      Status_Dokumen: 'Done'
    },
    {
      No: 43,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AYAMARU BARAT',
      Cell_ID: 'PAB0982_Ex_PAB0730',
      Site_Name: 'YABOK',
      File_Name: 'PAB0982_Ex_PAB0730_YABOK',
      Longitude: 132.98463,
      Latitude: -1.18982,
      Survey: 'Relok',
      Status_Dokumen: 'Done'
    },
    {
      No: 44,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO RAYA',
      Cell_ID: 'PAB0816',
      Site_Name: 'SRIRTABAM',
      File_Name: 'PAB0816_SRIRTABAM',
      Longitude: 132.34016,
      Latitude: -1.3063,
      Survey: 'Layak',
      Status_Dokumen: 'Ok',
      Keterangan: 'Revisi-Geser'
    },
    {
      No: 45,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO RAYA',
      Cell_ID: 'PAB0993_Ex_PAB0813',
      Site_Name: 'YUMAME',
      File_Name: 'PAB0993_Ex_PAB0813_YUMAME',
      Longitude: 132.30432,
      Latitude: -1.30266,
      Survey: 'Relok',
      Status_Dokumen: 'Done'
    },
    {
      No: 46,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO RAYA',
      Cell_ID: 'PAB0994_Ex-PAB0814',
      Site_Name: 'KAMBUSABO',
      File_Name: 'PAB0994_Ex-PAB0814_KAMBUSABO',
      Longitude: 132.30787,
      Latitude: -1.34684,
      Survey: 'Relok',
      Status_Dokumen: 'Done'
    },
    {
      No: 47,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO RAYA',
      Cell_ID: 'PAB0815',
      Site_Name: 'IKUF UTARA',
      File_Name: 'PAB0815_IKUF UTARA',
      Longitude: 132.3022,
      Latitude: -1.29679,
      Survey: 'Layak',
      Status_Dokumen: 'Ok'
    },
    {
      No: 48,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO RAYA',
      Cell_ID: 'PAB0817',
      Site_Name: 'FAITHOWES',
      File_Name: 'PAB0817_FAITHOWES',
      Longitude: 132.32863,
      Latitude: -1.32126,
      Survey: 'Layak',
      Status_Dokumen: 'Done'
    },
    {
      No: 49,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO BARAT',
      Cell_ID: 'PAB0678',
      Site_Name: 'FATASE',
      File_Name: 'PAB0678_FATASE',
      Longitude: 132.26883,
      Latitude: -1.37942,
      Survey: 'Layak',
      Status_Dokumen: 'Today'
    },
    {
      No: 50,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO BARAT',
      Cell_ID: 'PAB0679',
      Site_Name: 'WAYBOMATAH',
      File_Name: 'PAB0679_WAYBOMATAH',
      Longitude: 132.28852,
      Latitude: -1.4045,
      Survey: 'Layak',
      Status_Dokumen: 'Today'
    },
    {
      No: 51,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO BARAT',
      Cell_ID: 'PAB0978_Ex_PAB0680',
      Site_Name: 'HOSYOATA',
      File_Name: 'PAB0978_Ex_PAB0680_HOSYOATA',
      Longitude: 132.29016,
      Latitude: -1.37654,
      Survey: 'Relok',
      Status_Dokumen: 'Done'
    },
    {
      No: 52,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'AITINYO BARAT',
      Cell_ID: 'PAB0979_Ex_PAB0681',
      Site_Name: 'FATEM',
      File_Name: 'PAB0979_Ex_PAB0681_FATEM',
      Longitude: 132.27441,
      Latitude: -1.3512,
      Survey: 'Relok',
      Status_Dokumen: 'Done'
    },
    {
      No: 53,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'MARE',
      Cell_ID: 'PAB0731',
      Site_Name: 'SEYA',
      File_Name: 'PAB0731_SEYA',
      Longitude: 132.28262,
      Latitude: -1.01005,
      Survey: 'Layak',
      Status_Dokumen: 'Today'
    },
    {
      No: 54,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'MARE',
      Cell_ID: 'PAB0983_Ex_PAB0732',
      Site_Name: 'WABAN',
      File_Name: 'PAB0983_Ex_PAB0732_WABAN',
      Survey: 'Relok',
      Status_Dokumen: 'Reloc',
      Keterangan: 'No Candidate',
      Longitude: NaN,
      Latitude: NaN
    },
    {
      No: 55,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'MARE',
      Cell_ID: 'PAB0733',
      Site_Name: 'KOMBIF',
      File_Name: 'PAB0733_KOMBIF',
      Longitude: 132.2838,
      Latitude: -0.93321,
      Survey: 'Layak',
      Status_Dokumen: 'Today'
    },
    {
      No: 56,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'MARE',
      Cell_ID: 'PAB0734',
      Site_Name: 'RUFASES',
      File_Name: 'PAB0734_RUFASES',
      Longitude: 132.39264,
      Latitude: -1.01799,
      Survey: 'Layak',
      Status_Dokumen: 'Today'
    },
    {
      No: 57,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'MARE',
      Cell_ID: 'PAB0735',
      Site_Name: 'BAKRABI',
      File_Name: 'PAB0735_BAKRABI',
      Longitude: 132.29619,
      Latitude: -0.94373,
      Survey: 'Layak',
      Status_Dokumen: 'Today'
    },
    {
      No: 58,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'MARE',
      Cell_ID: 'PAB0736',
      Site_Name: 'NAFASI',
      File_Name: 'PAB0736_NAFASI',
      Longitude: 132.34434,
      Latitude: -0.94373,
      Survey: 'Layak',
      Status_Dokumen: 'Not Yet'
    },
    {
      No: 59,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'MAYBRAT',
      Kecamatan: 'MARE',
      Cell_ID: 'PAB0737',
      Site_Name: 'MAHOS',
      File_Name: 'PAB0737_MAHOS',
      Longitude: 132.27365,
      Latitude: -0.93093,
      Survey: 'Layak',
      Status_Dokumen: 'Today'
    },
    {
      No: 60,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'TAMBRAUW',
      Kecamatan: 'MIYAH SELATAN',
      Cell_ID: 'PAB0942_Ex_PAB0528',
      Site_Name: 'PUBUAN',
      File_Name: 'PAB0942_Ex_PAB0528_PUBUAN',
      Longitude: 133.27593,
      Latitude: -0.86194,
      Survey: 'Relok',
      Status_Dokumen: 'Not Yet'
    },
    {
      No: 61,
      Batch: '1A',
      Provinsi: 'Papua Barat',
      Kabupaten: 'TAMBRAUW',
      Kecamatan: 'KEBAR SELATAN',
      Cell_ID: 'PAB0951_Ex-PAB0581',
      Site_Name: 'IBUANARI',
      File_Name: 'PAB0951_Ex-PAB0581_IBUANARI',
      Longitude: 133.14526,
      Latitude: -0.84998,
      Survey: 'Relok',
      Status_Dokumen: 'Not Yet'
    }
  ]